---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cargo-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/bpfd/cargo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: target-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 7Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/bpfd/target
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cargo-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:
        2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: target-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:
        7Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpfd-builder
  labels:
    app: bpfd-builder
spec:
  selector:
    matchLabels:
      app: bpfd-builder
  replicas: 1
  template:
    metadata:
      name: bpfd-builder
      labels:
        app: bpfd-builder
    spec:
      containers:
      - name: bpfd-builder
        image: quay.io/mmoltras/devcontainers:bpfd
        imagePullPolicy: Never
        workingDir: ${HOME}/go/src/github.com/redhat-et/bpfd
        securityContext:
          privileged: true
        env:
        - name: CARGO_TARGET_DIR
          value: /root/target
        command:
        - /bin/bash
        stdin: true
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: bpfd-repo
          mountPath: ${HOME}/go/src/github.com/redhat-et/bpfd
        - name: libbpf-repo
          mountPath: ${HOME}/go/src/github.com/libbpf/libbpf
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: sys
          mountPath: /sys
        - name: cargo-pv-storage
          mountPath: /usr/local/cargo/registry
        - name: target-pv-storage
          mountPath: /root/target
      volumes:
        - name: bpfd-repo
          hostPath:
            path: ${HOME}/go/src/github.com/redhat-et/bpfd
        - name: libbpf-repo
          hostPath:
            path: ${HOME}/go/src/github.com/libbpf/libbpf
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: sys
          hostPath:
            path: /sys
        - name: cargo-pv-storage
          persistentVolumeClaim:
            claimName: cargo-pv-claim
        - name: target-pv-storage
          persistentVolumeClaim:
            claimName: target-pv-claim
