FROM fedora:43

RUN dnf install -y \
        clang \
        git \
        libbpf-devel \
        nodejs \
        openssl-devel \
        protobuf-devel \
        rustup-init && \
    rustup-init -y
