FROM fedora:41

ARG DEFAULT_GROUP
ARG DEFAULT_USER

RUN dnf install -y \
    autoconf \
    automake \
    bpftool \
    ccache \
    clang \
    cmake \
    diffutils \
    dnf-plugins-core \
    elfutils-libelf-devel \
    fzf \
    gcc \
    gcc-c++ \
    git \
    inotify-tools \
    kmod \
    libasan \
    libbpf-devel \
    libtool \
    libubsan \
    make \
    ncurses-devel \
    patch \
    perl-core \
    pkg-config \
    podman \
    podman-docker \
    procps \
    python3-pip \
    sudo \
    wget \
    which \
    zsh \
# Debugging packages
    clang-analyzer \
    clang-tools-extra \
    gdb \
# Dependencies for falcosecurity/testing
    golang \
# Dependencies needed to build falcosecurity/libs.
    c-ares-devel \
    grpc-cpp \
    grpc-devel \
    grpc-plugins \
    jq-devel \
    jsoncpp-devel \
    libb64-devel \
    libcurl-devel.x86_64 \
    libcurl.x86_64 \
    openssl-devel \
    tbb-devel \
    xz \
    zlib-devel && \
    dnf clean all && \
    groupadd -g $DEFAULT_GROUP molter && \
    useradd -m -l -u $DEFAULT_USER -g molter molter && \
    echo 'molter        ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers && \
    # Install NeoVim
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
    tar -C /opt -xzf nvim-linux-x86_64.tar.gz && \
    rm -f nvim-linux-x86_64.tar.gz && \
    # Install tree-sitter
    curl -LO https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz && \
    gunzip -c tree-sitter-linux-x64.gz > /usr/local/bin/tree-sitter && \
    chmod +x /usr/local/bin/tree-sitter && \
    rm -f tree-sitter-linux-x64.gz && \
# Set some symlinks to allow building of drivers.
    kernel_version=$(uname -r) && \
    ln -s "/host/lib/modules/$kernel_version" "/lib/modules/$kernel_version" && \
    ln -s "/host/usr/src/kernels/$kernel_version" "/usr/src/kernels/$kernel_version"

USER molter
WORKDIR /home/molter

# Install emscripten
RUN git clone https://github.com/emscripten-core/emsdk.git && \
    cd emsdk && ./emsdk install latest && \
    ./emsdk activate latest && \
    echo 'export EMSDK_QUIET=1' >> "${HOME}/.bashrc" && \
    echo 'source /emsdk/emsdk_env.sh' >> "${HOME}/.bashrc" && \
    # Install my dev environment
    # Clone my configuration
    git clone https://github.com/molter73/dotfiles "${HOME}/.config" && \
    # Install starship.rs
    curl -sS https://starship.rs/install.sh | sh -s -- --yes && \
    # Install my configuration
    rm -f "${HOME}/.zshrc" && \
    "${HOME}/.config/zsh/install.sh" && \
    "${HOME}/.config/scripts/install.sh" && \
    /opt/nvim-linux-x86_64/bin/nvim --headless "+Lazy! restore" +qa

COPY clangd.yaml /home/molter/.config/clangd/config.yaml
COPY compile-falco.sh /usr/local/bin/
COPY compile-libs.sh /usr/local/bin/

ENTRYPOINT ["/usr/bin/zsh"]
