apiVersion: apps/v1
kind: Deployment
metadata:
  name: libs-builder
  labels:
    app: libs-builder
spec:
  selector:
    matchLabels:
      app: libs-builder
  replicas: 1
  template:
    metadata:
      name: libs-builder
      labels:
        app: libs-builder
    spec:
      containers:
      - name: libs-builder
        image: quay.io/mmoltras/devcontainers:falco-libs-${FALCO_BUILDER_FLAVOR}
        imagePullPolicy: Never
        workingDir: ${HOME}/go/src/github.com/falcosecurity/libs
        securityContext:
          privileged: true
        env:
        - name: CMAKE_EXPORT_COMPILE_COMMANDS
          value: "ON"
        - name: HOST_ROOT
          value: /host
        - name: FALCO_DIR
          value: ${HOME}/go/src/github.com/falcosecurity/libs
        command:
        - /bin/bash
        stdin: true
        volumeMounts:
        - name: libs-repo
          mountPath: ${HOME}/go/src/github.com/falcosecurity/libs
        - name: src
          mountPath: /usr/src
        - name: modules
          mountPath: /lib/modules
        - name: bpf
          mountPath: /usr/include/bpf
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: dev
          mountPath: /host/dev
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: etc
          mountPath: /host/etc
          readOnly: true
        - name: usr-lib
          mountPath: /host/usr/lib
          readOnly: true
      volumes:
        - name: libs-repo
          hostPath:
            path: ${HOME}/go/src/github.com/falcosecurity/libs
        - name: src
          hostPath:
            path: /usr/src
        - name: modules
          hostPath:
            path: /lib/modules
        - name: bpf
          hostPath:
            path: /usr/include/bpf
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
        - name: usr-lib
          hostPath:
            path: /usr/lib
