image := "quay.io/mmoltras/devcontainers:falco-libs"
template := `pwd` / 'clangd.tpl.yaml'
clangd := `pwd` / 'clangd.yaml'

build: clang-config
    docker build \
        --tag {{image}} \
        --build-arg DEFAULT_GROUP=`id -g` \
        --build-arg DEFAULT_USER=`id -u` \
        -f Containerfile \
        `pwd`

clang-config: clean
    @envsubst < {{template}} > {{clangd}}

clean:
    @rm -f {{clangd}}

push:
    docker push {{image}}
