apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-builder
  labels:
    app: collector-builder
spec:
  selector:
    matchLabels:
      app: collector-builder
  replicas: 1
  template:
    metadata:
      name: collector-builder
      labels:
        app: collector-builder
    spec:
      containers:
      - name: collector-builder
        image: collector-devcontainer:latest
        imagePullPolicy: Never
        workingDir: ${HOME}/go/src/github.com/stackrox/collector
        securityContext:
          privileged: true
        env:
        - name: CMAKE_EXPORT_COMPILE_COMMANDS
          value: "ON"
        - name: DISABLE_PROFILING
          value: "true"
        - name: COLLECTOR_HOST_ROOT
          value: /host
        command:
        - /bin/bash
        stdin: true
        volumeMounts:
        - name: collector-repo
          mountPath: ${HOME}/go/src/github.com/stackrox/collector
        - name: dev
          mountPath: /host/dev
          readOnly: true
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: etc
          mountPath: /host/etc
          readOnly: true
        - name: usr-lib
          mountPath: /host/usr/lib
          readOnly: true
      volumes:
        - name: collector-repo
          hostPath:
            path: ${HOME}/go/src/github.com/stackrox/collector
        - name: dev
          hostPath:
            path: /dev
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: etc
          hostPath:
            path: /etc
        - name: usr-lib
          hostPath:
            path: /usr/lib
