FROM quay.io/stackrox-io/collector-builder:master

ARG DEFAULT_GROUP
ARG DEFAULT_USER

RUN dnf install -y epel-release && \
    dnf remove -y clang llvm && \
    dnf install -y \
        ccache \
        clang \
        clang-analyzer \
        clang-tools-extra \
        fzf \
        inotify-tools \
        llvm \
        podman-docker \
        sudo \
        zsh && \
    dnf clean all && \
    groupadd -g "$DEFAULT_GROUP" molter && \
    useradd -m -l -u "$DEFAULT_USER" -g molter molter && \
    echo 'molter        ALL=(ALL)       NOPASSWD: ALL' >> /etc/sudoers && \
    # Install NeoVim
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz && \
    tar -C /opt -xzf nvim-linux-x86_64.tar.gz && \
    rm -f nvim-linux-x86_64.tar.gz && \
    # Install tree-sitter
    curl -LO https://github.com/tree-sitter/tree-sitter/releases/latest/download/tree-sitter-linux-x64.gz && \
    gunzip -c tree-sitter-linux-x64.gz > /usr/local/bin/tree-sitter && \
    chmod +x /usr/local/bin/tree-sitter && \
    rm -f tree-sitter-linux-x64.gz

USER molter
WORKDIR /home/molter

# Install my dev environment
RUN git clone https://github.com/molter73/dotfiles "${HOME}/.config" && \
    # Install starship.rs
    curl -sS https://starship.rs/install.sh | sh -s -- --yes && \
    # Install my configuration
    rm -f "${HOME}/.zshrc" && \
    "${HOME}/.config/zsh/install.sh" && \
    "${HOME}/.config/scripts/install.sh" && \
    /opt/nvim-linux-x86_64/bin/nvim --headless "+Lazy! restore" +qa

COPY clangd.yaml /home/molter/.config/clangd/config.yaml

# scan-view default port
EXPOSE 8181

ENTRYPOINT ["/usr/bin/zsh"]
