name: Build and push devcontainer images
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image:
        - collector
        - falco-libs
    steps:
    - uses: actions/checkout@v3
    - uses: taiki-e/install-action@just


    - name: Build
      run: |
        just ${{ matrix.image }}/build

    - name: Login to Quay.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_TOKEN }}

    - name: Build and push
      if: github.event_name != 'pull_request'
      run: |
        just ${{ matrix.image }}/push
